server:
  port : 8081

spring:
  #https://www.baeldung.com/database-migrations-with-flyway
  #docker run --env=POSTGRES_PASSWORD=admin -p 5433:5432 -d postgres:latest
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin

springdoc:
  swagger-ui:
    url: /v3/api-docs.yaml

