server:
  port: 8081

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin

springdoc:
  swagger-ui:
    url: /v3/api-docs.yaml

