server:
    port: 8090

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Ale05deserto

springdoc:
  swagger-ui:
    url: /v3/api-docs.yaml