version: "3.7"

services:
  app:
    image: ygmarchi/codylab-rookie:1.0-SNAPSHOT
    # http://localhost:8090/swagger-ui/index.html
    ports:
      - 8090:8080
    environment:
      POSTGRES_HOST: postgres


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
